kind = "mobile"
previewPath = "/mobile/"
title = "Auto Reaction Bot Mobile"
version = "1.0.0"
id = "artifacts/auto-reaction-bot-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 22836

[services.development]
run = "pnpm --filter @workspace/auto-reaction-bot-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/auto-reaction-bot-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/auto-reaction-bot-mobile", "run", "serve" ]

[services.env]
PORT = "22836"
BASE_PATH = "/mobile/"
